<a href="https://colab.research.google.com/github/snehalnandi/React-Data-Dashboard/blob/main/02_My_Solo_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
shop_data = {
    'Item' : ['tea', 'Biscuits','Sugar'],
    'Price' : [20,50,40]
}
my_shop_df = pd.DataFrame(shop_data)

my_shop_df

       Item  Price
0       tea     20
1  Biscuits     50
2     Sugar     40

In [9]:
Total_Price = my_shop_df['Price'].sum()

print ("Your Total is" , Total_Price  )

Your Total is 110

In [21]:
cheap_price = my_shop_df[my_shop_df['Price']<35]

cheap_price

print("mm you can buy ....." ,  cheap_price )

mm you can buy .....   Item  Price
0  tea     20

In [25]:
restaurant_df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv')
restaurant_df.head(10)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [27]:
restaurant_df.describe().round(2)

       total_bill     tip    size
count      244.00  244.00  244.00
mean        19.79    3.00    2.57
std          8.90    1.38    0.95
min          3.07    1.00    1.00
25%         13.35    2.00    2.00
50%         17.80    2.90    2.00
75%         24.13    3.56    3.00
max         50.81   10.00    6.00

In [28]:
high_rollers = restaurant_df [restaurant_df['total_bill']>40]
high_rollers

     total_bill    tip     sex smoker   day    time  size
59        48.27   6.73    Male     No   Sat  Dinner     4
95        40.17   4.73    Male    Yes   Fri  Dinner     4
102       44.30   2.50  Female    Yes   Sat  Dinner     3
142       41.19   5.00    Male     No  Thur   Lunch     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
182       45.35   3.50    Male    Yes   Sun  Dinner     3
184       40.55   3.00    Male    Yes   Sun  Dinner     2
197       43.11   5.00  Female    Yes  Thur   Lunch     4
212       48.33   9.00    Male     No   Sat  Dinner     4